[package]
name = "port4k-admin"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }


[dependencies]
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }