[package]
name = "port4k-core"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }


[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }