pub const BANNER: &str = concat!(
    "\n",
    "\x1b[36m",
    "______          _       ___ _     \n",
    "| ___ \\        | |     /   | |    \n",
    "| |_/ /__  _ __| |_   / /| | | __ \n",
    "|  __/ _ \\| '__| __| / /_| | |/ / \n",
    "| | | (_) | |  | |_  \\___  |   <  \n",
    "\\_|  \\___/|_|   \\__|     |_/_|\\_\\ \n",
    "\x1b[0m\n"
);

pub const ENTRY: &str = concat!(
    "\n",
    "\x1b[1;35m", "★ WELCOME TO PORT4K ★", "\x1b[0m", "\n",
    "\n",
    "\x1b[36m",
    "A world of rooms, puzzles, and adventure - built by players and shaped by your\n",
    "choices. Explore hand-crafted spaces, read subtle clues, flip levers, outwit\n",
    "locks, and discover hidden links between worlds. Build your own rooms with\n",
    "Lua, publish them, and watch others attempt (and break!) your designs. Your\n",
    "progress persists: XP, skills, coins, and story flags that unlock new paths\n",
    "over time.\n",
    "\x1b[0m",
    "================================================\n",
    "\x1b[33m•\x1b[0m Explore player-built worlds\n",
    "\x1b[33m•\x1b[0m Forge your own rooms with Lua scripting\n",
    "\x1b[33m•\x1b[0m Grow your character: XP, skills, items\n",
    "\x1b[33m•\x1b[0m Classic MUD feel with modern polish\n",
    "================================================\n",
    "\x1b[1mGetting started\x1b[0m\n",
    "  ", "\x1b[32mabout\x1b[0m", "   read the story of port4k\n",
    "  ", "\x1b[32mregister <name>\x1b[0m", "   create a new character\n",
    "  ", "\x1b[32mlogin <name>\x1b[0m",    "      access your account (Telnet two-step supported)\n",
    "  ", "\x1b[32mhelp\x1b[0m",            "              list commands | ",
    "\x1b[31mquit\x1b[0m", " to exit\n",
    "------------------------------------------------\n",
    "\x1b[36m", "Pro tip: Start with ", "\x1b[32mlook\x1b[36m",
    ", then try ", "\x1b[32mexamine door\x1b[36m", ", ",
    "\x1b[32mopen door\x1b[36m", " or ", "\x1b[32mgo east\x1b[36m", ".", "\x1b[0m", "\n",
);